openapi: 3.2.0
info:
  version: '0.3'
  title: HiPay Marketplace Identification API
  description: The implementation of HiPay Marketplace involves establishing connections between your marketplace platform and HiPay based on a simple integration through a set of APIs.
servers:
- url: https://test-professional.hipay.com/api
tags:
- name: Identification
  description: Manage your identification documents
paths:
  /identification.{_format}:
    get:
      description: '### Information

        Get the list of all identification documents for a user-space


        For more information, please read the HiPay Marketplace Account creation section.'
      operationId: get_Identification
      parameters:
      - in: path
        name: _format
        required: true
        schema:
          type: string
          enum:
          - json
          - xml
          default: json
      - description: Account ID if operations must be made on an account other than yours (you must have specific rights on this account).
        in: header
        name: php-auth-subaccount-id
        schema:
          type: integer
      - description: Account login (email) if operations must be made on an account other than yours (you must have specific rights on this account).
        in: header
        name: php-auth-subaccount-login
        schema:
          type: string
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                properties:
                  code:
                    description: Status code of the answer. 0 => Successful response 2 => Missing parameter 3 => Invalid parameter 7 => Not found 13 => An error occurred, please try again 400 => Bad request
                    format: int32
                    type: integer
                  message:
                    description: Description of the answer.
                    type: string
                  user_space:
                    description: integer
                    format: int32
                    type: integer
                  identification_status:
                    description: "###  Identification status\n\n  - `Unidentified`\n  - `In progress`\n  - `Identified`"
                    type: string
                  documents:
                    description: Array of objects (IdentificationDocumentResponse).
                    items:
                      description: Array of objects (IdentificationDocumentResponse).
                      properties:
                        type:
                          description: "### Type\n\n  - `-1`: Missing document\n  - `1`: Identity card\n  - `2`: Proof of address\n  - `4`: Company Registration\n  - `5`: Distribution of power\n  - `6`: Bank\n  - `9`: Tax status\n  - `11`: President of the association\n  - `12`: Official journal\n  - `13`: Association status\n  - `14`: Licence"
                          format: int32
                          type: integer
                        label:
                          description: string
                          type: string
                        status_code:
                          description: "###  Status\n\n  - `0`: new\n  - `1`: waiting\n  - `2`: validated\n  - `3`: refused\n  - `4`: deleted"
                          format: int32
                          type: integer
                        status_label:
                          description: string
                          type: string
                        message:
                          description: string
                          type: string
                    type: array
        '400':
          description: Validation failed.
        '401':
          description: Authentication failed.
      summary: Get the list of all identification documents for a user-space
      tags:
      - Identification
      security:
      - basicAuth: []
    post:
      description: '### Information


        Upload identification documents. Uploaded documents can''t exceed 15MB.


        __Type of document for a customer account__

        - `1`: Copy of a valid identification document


        __Type of document for a merchant account (corporation)__

        - `1`: Copy of a valid identification document of the legal representative. *Deprecated, please use type 1 for all ID documents*


        - `4`: Document certifying Company registration


        - `5`: Signed Articles of Association with the division of powers (featuring the address of the head office, the name of the company and the name of the legal representative)


        __Type of document for a merchant account (corporation) with a gambling licence__

        - `1`: Copy of a valid identification document of the legal representative. *Deprecated, please use type 1 for all ID documents*


        - `4`: Document certifying Company registration


        - `5`: Signed Articles of Association with the division of powers (featuring the address of the head office, the name of the company and the name of the legal representative)


        - `14`: Gambling licence document


        __Type of document for a merchant account (person)__

        - `1`: Copy of a valid identification document of the legal representative. *Deprecated, please use type 1 for all ID documents*


        - `8`: Document certifying registration


        - `9`: Document certifying tax status


        __In test environment__


        You can choose if the document will be accepted or not by changing the 3 first characters of the uploaded file name.

        - Filename starts with `01_`: document will be refused because unrecognized


        - Filename starts with `02_`: document will be refused because falsified


        - Filename starts with `03_`: document will be refused because unreadable


        - Filename starts with `06_`: document will be refused because inconsistent


        - Filename starts with `07_`: document will be refused because expired


        - Any other name : document will be automatically accepted


        ### Account creation step 3/3

        The agent sends us the account number and the identification/KYC information with this API. HiPay validates the identification/KYC information within three days and sends the agent a notification confirming that the merchant is fully operational.'
      operationId: post_Identification
      parameters:
      - in: path
        name: _format
        required: true
        schema:
          type: string
          enum:
          - json
          - xml
          default: json
      - description: Account ID if operations must be made on an account other than yours (you must have specific rights on this account).
        in: header
        name: php-auth-subaccount-id
        schema:
          type: integer
      - description: Account login (email address) if operations must be made on an account other than yours (you must have specific rights on this account).
        in: header
        name: php-auth-subaccount-login
        schema:
          type: string
      responses:
        '200':
          description: Success response.
          content:
            application/json:
              schema:
                properties:
                  code:
                    description: Status code of the answer. 0 => Document successfully uploaded 414 => User space already identified 415 => A document of this type is already waiting for validation
                    format: int32
                    type: integer
                  message:
                    description: Description of the answer.
                    type: string
                  user_space:
                    description: integer
                    format: int32
                    type: integer
                  type:
                    description: "### Type\n   - `-1` : Missing document\n   - `1` : Identity card\n   - `2` : Proof of address\n   - `4`: Company Registration\n   - `5` : Distribution of power\n   - `6` : Bank\n   - `9` : Tax status\n   - `11` : President of the association\n   - `12` : Official journal\n   - `13` : Association status\n   - `14` : Licence"
                    format: int32
                    type: integer
                  validity_date:
                    description: DateTime
                    format: date-time
                    type: string
        '400':
          description: Validation failed.
        '401':
          description: Authentication failed.
      summary: Upload identification documents
      tags:
      - Identification
      security:
      - basicAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                type:
                  type: integer
                  format: int32
                  default: '1'
                  description: Type of document.
                file:
                  type: string
                  format: binary
                  description: File to upload (jpg, gif, png, pdf). For ID documents, if you have a single file regrouping the front and back sides, please use only this field.
                back:
                  type: string
                  format: binary
                  description: BBack of file to upload (jpg, gif, png, pdf). Only to be used in case the front and back sides of the ID document are in two separate files
                validity_date:
                  type: string
                  format: date
                  default: '2020-11-20'
                  description: Expiration date of your document.
              required:
              - type
              - file
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
