openapi: 3.2.0
info:
  description: '## Description

    The HiPay POS API allows you to trigger in-store payments by:

    - waking a point-of-sale (POS) payment terminal with the payment information (amount, currency, etc.)

    - creating the related transaction in HiPay Console, your dedicated management interface.'
  title: POS Connector API
  version: 1.2.0
servers:
- url: https://cloudrun-api-yugcnet4yq-ew.a.run.app/
  description: Stage
tags:
- name: Connector
paths:
  /v1/connector/healthcheck:
    get:
      description: Health check
      responses:
        '200':
          description: Health check OK
      operationId: healthcheck
      tags:
      - Connector
      summary: Healthcheck
      x-summary-source: derived
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
