openapi: 3.2.0
info:
  version: '0.3'
  title: HiPay Marketplace Balance API
  description: The implementation of HiPay Marketplace involves establishing connections between your marketplace platform and HiPay based on a simple integration through a set of APIs.
servers:
- url: https://test-professional.hipay.com/api
tags:
- name: Balance
  description: Manage the balance of a HiPay account
paths:
  /user-account/balance.{_format}:
    get:
      description: '### Information

        Get the balance of a specific HiPay account.'
      operationId: get_user-account_balance
      parameters:
      - in: path
        name: _format
        required: true
        schema:
          type: string
          enum:
          - json
          - xml
          default: json
      - description: Date for the balance.
        in: query
        name: date
        schema:
          type: string
          format: date
          default: '2018-02-01'
      - description: Account ID if operations must be made on an account other than yours (you must have specific rights on this account).
        in: header
        name: php-auth-subaccount-id
        schema:
          type: integer
      - description: Account login (email address) if operations must be made on an account other than yours (you must have specific rights on this account).
        in: header
        name: php-auth-subaccount-login
        schema:
          type: string
      responses:
        '200':
          description: Success response.
          content:
            application/json:
              schema:
                properties:
                  code:
                    description: Status code of the answer.
                    format: int32
                    type: integer
                  date:
                    description: Date for the balance (yyyy-mm-dd).
                    format: date-time
                    type: string
                  message:
                    description: Description of the answer.
                    type: string
                  balances:
                    description: List of account and sub-account balances.
                    type: array
                    items:
                      type: object
                      description: List of account and sub-account balances.
                      properties:
                        user_account_id:
                          description: Account ID.
                          format: int32
                          type: integer
                        user_account_type:
                          description: "### Account type\n\n   - `1`: Main account\n   - `2`: secondary account\n   - `3`: original account"
                          type: string
                        balance:
                          description: Account balance.
                          type: string
                        currency:
                          description: Account currency.
                          type: string
                        money_available_for_withdrawal:
                          description: Amount available for withdrawal.
                          type: string
        '400':
          description: Validation failed.
        '401':
          description: Authentication failed.
      summary: Get the balance of a HiPay account
      tags:
      - Balance
      security:
      - basicAuth: []
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
