openapi: 3.2.0
info:
  version: '0.3'
  title: HiPay Marketplace Constants API
  description: The implementation of HiPay Marketplace involves establishing connections between your marketplace platform and HiPay based on a simple integration through a set of APIs.
servers:
- url: https://test-professional.hipay.com/api
tags:
- name: Constants
  description: Manage your account with our API tools
paths:
  /tools/bank-info-fields/{country}/{locale}.{_format}:
    get:
      summary: Get bank details required for a HiPay account depending on its country
      description: '### Information


        Get bank details required for a HiPay account depending on its country.'
      parameters:
      - in: path
        name: country
        required: true
        description: 'Enter country code [using ISO_3166-1 convention.](https://en.wikipedia.org/wiki/ISO_3166-1#Officially_assigned_code_elements)

          Examples of values: `FR`, `AL`, `AU`, `PT`, `US`...'
        schema:
          type: string
          default: FR
      - in: path
        name: locale
        required: true
        description: 'Enter locale code [using this convention.](https://www.softaculous.com/docs/Scripts_Language_Codes)

          Examples of values: `fr_FR`, `de_DE`, `es_ES`, `uk_UA`...'
        schema:
          type: string
          default: fr_FR
      - in: path
        name: _format
        required: true
        schema:
          type: string
          enum:
          - json
          - xml
          default: json
      responses:
        '200':
          description: Success response.
          content:
            application/json:
              schema:
                properties:
                  code:
                    description: Status code of the answer.
                    format: int32
                    type: integer
                  message:
                    description: Description of the answer.
                    type: string
                  country:
                    description: Country to get bank info fields.
                    type: string
                  fields:
                    description: Required bank fields.
                    items:
                      description: Required bank fields.
                      properties:
                        code:
                          description: string
                          type: string
                        label:
                          description: string
                          type: string
                    type: array
        '400':
          description: Validation failed.
        '401':
          description: Authentication failed.
      tags:
      - Constants
      operationId: getToolsBankInfoFieldsByCountryByLocale}{Format
      x-operation-id-source: derived
  /tools/business-lines/{locale}.{_format}:
    get:
      summary: Return business lines
      description: '### Information


        Return business lines.'
      parameters:
      - in: path
        name: locale
        required: true
        description: 'Enter locale code [using this convention.](https://www.softaculous.com/docs/Scripts_Language_Codes)

          Examples of values: `fr_FR`, `de_DE`, `es_ES`, `uk_UA`...'
        schema:
          type: string
          default: fr_FR
      - in: path
        name: _format
        required: true
        schema:
          type: string
          enum:
          - json
          - xml
          default: json
      responses:
        '200':
          description: Success response.
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: integer
                    format: int32
                    description: Status code of the answer.
                  message:
                    type: string
                    description: Description of the answer.
                  business_lines:
                    type: array
                    items:
                      description: array of objects (BusinessLineEntity)
                      properties:
                        id:
                          type: integer
                          format: int32
                          description: integer
                        label:
                          type: string
                          description: string
                    description: array of objects (BusinessLineEntity)
        '400':
          description: Validation failed.
        '401':
          description: Authentication failed.
      tags:
      - Constants
      operationId: getToolsBusinessLinesByLocale}{Format
      x-operation-id-source: derived
  /tools/locale/codes.{_format}:
    get:
      summary: Return locales codes and names
      description: '### Information


        Return locales codes and names.'
      parameters:
      - in: path
        name: _format
        required: true
        schema:
          type: string
          enum:
          - json
          - xml
          default: json
      responses:
        '200':
          description: Success response.
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: integer
                    format: int32
                    description: Status code of the answer.
                  message:
                    type: string
                    description: Description of the answer.
                  locales:
                    type: array
                    items:
                      description: Required bank fields.
                      properties:
                        code:
                          description: string
                          type: string
                        label:
                          description: string
                          type: string
                    description: array of objects (CodeLabelResponse)
        '400':
          description: Validation failed.
        '401':
          description: Authentication failed.
      tags:
      - Constants
      operationId: getToolsLocaleCodes{Format}
      x-operation-id-source: derived
  /tools/locale/countries/{locale}.{_format}:
    get:
      summary: Return locales codes and names
      description: '### Information


        Return countries codes and labels by locale.'
      parameters:
      - in: path
        name: locale
        required: true
        description: 'Enter locale code [using this convention.](https://www.softaculous.com/docs/Scripts_Language_Codes)

          Examples of values: `fr_FR`, `de_DE`, `es_ES`, `uk_UA`...'
        schema:
          type: string
          default: fr_FR
      - in: path
        name: _format
        required: true
        schema:
          type: string
          enum:
          - json
          - xml
          default: json
      responses:
        '200':
          description: Success response.
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: integer
                    format: int32
                    description: Status code of the answer.
                  message:
                    type: string
                    description: Description of the answer.
                  countries:
                    type: array
                    items:
                      description: Required bank fields.
                      properties:
                        code:
                          description: string
                          type: string
                        label:
                          description: string
                          type: string
                    description: array of objects (CodeLabelResponse)
        '400':
          description: Validation failed.
        '401':
          description: Authentication failed.
      tags:
      - Constants
      operationId: getToolsLocaleCountriesByLocale}{Format
      x-operation-id-source: derived
  /tools/locale/currencies/{locale}.{_format}:
    get:
      summary: Return currencies codes and labels by locale
      description: '### Information


        Return currencies codes and labels by locale.'
      parameters:
      - in: path
        name: locale
        required: true
        description: 'Enter locale code [using this convention.](https://www.softaculous.com/docs/Scripts_Language_Codes)

          Examples of values: `fr_FR`, `de_DE`, `es_ES`, `uk_UA`...'
        schema:
          type: string
          default: fr_FR
      - in: path
        name: _format
        required: true
        schema:
          type: string
          enum:
          - json
          - xml
          default: json
      responses:
        '200':
          description: Success response.
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: integer
                    format: int32
                    description: Status code of the answer.
                  message:
                    type: string
                    description: Description of the answer.
                  currencies:
                    type: array
                    items:
                      description: Required bank fields.
                      properties:
                        code:
                          description: string
                          type: string
                        label:
                          description: string
                          type: string
                    description: array of objects (CodeLabelResponse)
        '400':
          description: Validation failed.
        '401':
          description: Authentication failed.
      tags:
      - Constants
      operationId: getToolsLocaleCurrenciesByLocale}{Format
      x-operation-id-source: derived
  /tools/locale/timezones.{_format}:
    get:
      summary: Return timezones
      description: '### Information


        Return timezones.'
      parameters:
      - in: path
        name: _format
        required: true
        schema:
          type: string
          enum:
          - json
          - xml
          default: json
      responses:
        '200':
          description: Success response.
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: integer
                    format: int32
                    description: Status code of the answer.
                  message:
                    type: string
                    description: Description of the answer.
                  timezones:
                    type: array
                    items:
                      description: Required bank fields.
                      properties:
                        code:
                          description: string
                          type: string
                        label:
                          description: string
                          type: string
                    description: array of objects (CodeLabelResponse)
        '400':
          description: Validation failed.
        '401':
          description: Authentication failed.
      tags:
      - Constants
      operationId: getToolsLocaleTimezones{Format}
      x-operation-id-source: derived
  /tools/website-topics/{business_line_id}/{locale}.{_format}:
    get:
      summary: Return website topics
      description: '### Information


        Return website topics.'
      parameters:
      - in: path
        name: locale
        required: true
        description: 'Enter locale code [using this convention.](https://www.softaculous.com/docs/Scripts_Language_Codes)

          Examples of values: `fr_FR`, `de_DE`, `es_ES`, `uk_UA`...'
        schema:
          type: string
          default: fr_FR
      - in: path
        name: business_line_id
        required: true
        schema:
          type: string
          default: '2'
      - in: path
        name: _format
        required: true
        schema:
          type: string
          enum:
          - json
          - xml
          default: json
      responses:
        '200':
          description: Success response.
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: integer
                    format: int32
                    description: Status code of the answer.
                  message:
                    type: string
                    description: Description of the answer.
                  business_line_id:
                    type: integer
                    format: int32
                    description: integer
                  website_topics:
                    type: array
                    items:
                      description: array of objects (TopicEntity)
                      properties:
                        id:
                          type: integer
                          format: int32
                          description: integer
                        label:
                          type: string
                          description: string
                    description: array of objects (TopicEntity)
        '400':
          description: Validation failed.
        '401':
          description: Authentication failed.
      tags:
      - Constants
      operationId: getToolsWebsiteTopicsByBusinessLineIdByLocale}{Format
      x-operation-id-source: derived
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
