openapi: 3.2.0
info:
  version: '0.3'
  title: HiPay Marketplace Captcha Generation API
  description: The implementation of HiPay Marketplace involves establishing connections between your marketplace platform and HiPay based on a simple integration through a set of APIs.
servers:
- url: https://test-professional.hipay.com/api
tags:
- name: captcha-generation
  description: Generate captcha
paths:
  /tools/captcha.{_format}:
    get:
      operationId: get_Captcha-generation
      summary: Generate a captcha
      description: '### Information


        Generate a captcha.'
      parameters:
      - in: path
        name: _format
        required: true
        schema:
          type: string
          enum:
          - json
          - xml
          default: json
      responses:
        '201':
          description: Success response.
          content:
            application/json:
              schema:
                properties:
                  code:
                    description: Status code of the answer.
                    format: int32
                    type: integer
                  message:
                    description: Description of the answer.
                    type: string
                  captcha_id:
                    description: Captcha ID.
                    format: int32
                    type: integer
                  captcha_img:
                    description: Captcha image.
                    type: string
        '400':
          description: Validation failed.
        '401':
          description: Authentication failed.
      tags:
      - captcha-generation
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
