openapi: 3.2.0
info:
  version: '0.3'
  title: HiPay Marketplace Invoice API
  description: The implementation of HiPay Marketplace involves establishing connections between your marketplace platform and HiPay based on a simple integration through a set of APIs.
servers:
- url: https://test-professional.hipay.com/api
tags:
- name: Invoice
  description: Manage marketplace invoices
paths:
  /marketplace/invoice.{_format}:
    get:
      summary: List marketplace invoices
      description: '### Information

        List marketplace invoices.'
      parameters:
      - in: path
        name: _format
        required: true
        schema:
          type: string
          enum:
          - json
          - xml
          default: json
      - in: query
        description: Invoice reference
        name: reference
        schema:
          type: string
      - in: query
        required: true
        description: Invoices year
        name: year
        schema:
          type: integer
          format: int32
          default: 2018
      responses:
        '200':
          description: Success response.
        '400':
          description: Validation failed.
      tags:
      - Invoice
      security:
      - basicAuth: []
      operationId: getMarketplaceInvoice{Format}
      x-operation-id-source: derived
  /marketplace/invoice/{reference}.{_format}:
    get:
      summary: Download an invoice
      description: '### Information

        Download an invoice.'
      parameters:
      - in: path
        name: reference
        required: true
        schema:
          type: integer
          default: '1'
      - in: path
        name: _format
        required: true
        schema:
          type: string
          enum:
          - json
          - xml
          default: json
      responses:
        '200':
          description: PDF document successfully returned
        '403':
          description: Access forbidden.
        '404':
          description: Invoice not found.
      tags:
      - Invoice
      security:
      - basicAuth: []
      operationId: getMarketplaceInvoiceByReference}{Format
      x-operation-id-source: derived
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
